import { buildCalculator, sqmInput } from "../helpers";
import type { CalculatorConfig, CalculatorTier } from "../types";

const TILE_TIERS: CalculatorTier[] = [
  {
    id: "perus",
    label: "Perustaso",
    subtitle: "250 €/m²",
    overrides: { laatat: 250 },
  },
  {
    id: "premium",
    label: "Premium",
    subtitle: "500 €/m²",
    overrides: { laatat: 500 },
  },
];

export const SISATILAT_CALCULATORS: CalculatorConfig[] = [
  buildCalculator({
    slug: "kylpyhuone",
    title: "Kylpyhuoneremontin hintalaskuri",
    pageTitle: "Kylpyhuoneremontti laskuri — arvioi remontin hinta",
    metaDescription:
      "Laske kylpyhuoneremontin hinta-arvio: purku, vesieristys, laatoitus, LVI ja kalusteet.",
    intro:
      "Arvioi kylpyhuoneremontin kustannukset. Hinnat perustuvat suomalaisiin keskiarvoihin — muokkaa rivejä tarpeen mukaan.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Lattian pinta-ala", 5, { min: 1, max: 30 }),
    tiers: TILE_TIERS,
    defaultTierId: "perus",
    lines: [
      {
        id: "purku",
        label: "Purkutyöt ja jätehuolto",
        description: "Vanhojen kalusteiden, laattojen ja mahdollisten valujen purku sekä jätemaksut.",
        unit: "per_primary",
        amount: 200,
        minAmount: 1000,
        searchHint: "kylpyhuoneen purkutyöt hinta",
      },
      {
        id: "vesieristys",
        label: "Vesieristys ja pohjatyöt",
        description: "Seinien ja lattian suoristus, tasoitus sekä sertifioitu vesieristys.",
        unit: "per_primary",
        amount: 300,
        searchHint: "kylpyhuoneen vesieristys hinta neliö",
      },
      {
        id: "laatoitus-tyo",
        label: "Laatoitustyö",
        description: "Seinien ja lattian laatoitus sekä saumaustyöt (työn osuus).",
        unit: "per_primary",
        amount: 400,
        searchHint: "laatoitus työ hinta neliö",
      },
      {
        id: "laatat",
        label: "Laatat ja pintamateriaalit",
        description: "Laatat, kiinnityslaastit ja sauma-aineet (materiaalien osuus).",
        unit: "per_primary",
        amount: 250,
        searchHint: "kylpyhuone laatta hinta eur neliö",
      },
      {
        id: "lvi-sahko",
        label: "LVI- ja sähkötyöt",
        description: "Putkien linjaukset, lattiakaivo, hanat, suihku ja valaistus.",
        unit: "fixed",
        amount: 2500,
        searchHint: "kylpyhuone putkityöt hinta",
      },
      {
        id: "kalusteet",
        label: "Kalusteet",
        description: "Allas, kaapit, wc-istuin ja hanat (hankintahinta).",
        unit: "fixed",
        amount: 1500,
        searchHint: "kylpyhuonekalusteet hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko kylpyhuoneremontti maksaa neliöltä?",
        a: "Laskurin oletus ({defaultSize}, perustaso) antaa {perUnitMid}/{primaryUnit}, eli kokonaisuutena noin {totalMid}. Tyypillinen haarukka samalla kohteella on {totalRange}.",
      },
      {
        q: "Mitä maksaa kylpyhuoneen vesieristys?",
        a: "Pelkkä vesieristys 500–2 500 €. Yhdessä laatoituksen kanssa 2 000–5 000 €. Laskurin rivihinta ({line:vesieristys:label}): {line:vesieristys:range}/{primaryUnit} (noin {line:vesieristys:mid}/{primaryUnit}).",
      },
    ],
    scopeTitle: "Miten kylpyhuoneremontin hinta muodostuu?",
    scopeParagraphs: [
      "Suurimmat erät ovat laatoitus (työ + materiaalit), LVI- ja sähkötyöt sekä vesieristys.",
      "Neliöhinta nousee, jos siirretään lattiakaivoa tai vesipisteitä.",
      "Kotitalousvähennys (35 % työn osuudesta) alentaa lopullista kustannusta.",
    ],
    ctaLabel: "Kilpailuta kylpyhuoneremontti ilmaiseksi",
  }),

  buildCalculator({
    slug: "keittio",
    title: "Keittiöremontin hintalaskuri",
    pageTitle: "Keittiöremontti laskuri — arvioi remontin hinta",
    metaDescription:
      "Laske keittiöremontin hinta-arvio: purku, kalusteet, työt ja kodinkoneet.",
    intro: "Keittiöremontin hinta riippuu kalusteista, kodinkoneista ja sähkö-/putkityöstä.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Keittiön pinta-ala", 12, { min: 4, max: 40 }),
    tiers: [
      { id: "perus", label: "Perustaso", overrides: { kalusteet: 4000 } },
      { id: "premium", label: "Premium", overrides: { kalusteet: 9000 } },
    ],
    defaultTierId: "perus",
    lines: [
      {
        id: "purku",
        label: "Purkutyöt ja jäte",
        description: "Vanhojen kalusteiden purku ja jätehuolto.",
        unit: "fixed",
        amount: 800,
        searchHint: "keittiön purkutyöt hinta",
      },
      {
        id: "kalusteet",
        label: "Keittiökalusteet",
        description: "Kaapit, työtasot ja vetimet.",
        unit: "fixed",
        amount: 4000,
        searchHint: "keittiökalusteet hinta",
      },
      {
        id: "tyo",
        label: "Asennustyö",
        description: "Kalusteiden asennus, listat ja viimeistely.",
        unit: "per_primary",
        amount: 200,
        searchHint: "keittiön asennus hinta neliö",
      },
      {
        id: "kodinkoneet",
        label: "Kodinkoneet",
        description: "Uuni, liesi, astianpesukone, jääkaappi (hankinta).",
        unit: "fixed",
        amount: 2500,
        searchHint: "keittiökodinkoneet hinta paketti",
      },
      {
        id: "sahko-lvi",
        label: "Sähkö- ja LVI-työt",
        description: "Pisteiden siirrot, putket ja ilmanvaihto.",
        unit: "fixed",
        amount: 1500,
        searchHint: "keittiö sähkötyöt hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko keittiöremontti maksaa?",
        a: "Kokonaisuus on tyypillisesti 10 000–40 000 € riippuen kalusteista.",
      },
    ],
    scopeTitle: "Keittiöremontin kustannukset",
    scopeParagraphs: [
      "Kalusteet ja kodinkoneet ovat suurin kustannuserä. Työ on noin 800–1 500 €/m².",
    ],
    ctaLabel: "Kilpailuta keittiöremontti",
  }),

  buildCalculator({
    slug: "wc-remontti",
    title: "WC-remontin hintalaskuri",
    pageTitle: "WC-remontti laskuri — arvioi remontin hinta",
    metaDescription: "Arvioi WC-remontin hinta: purku, laatoitus, putket ja kalusteet.",
    intro: "Pienempi wc-remontti maksaa vähemmän kuin täysi kylpyhuone, mutta neliöhinta on korkeampi.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("WC:n lattia-ala", 2, { min: 1, max: 8 }),
    lines: [
      {
        id: "purku",
        label: "Purkutyöt",
        description: "Vanhojen pintojen ja kalusteiden purku.",
        unit: "fixed",
        amount: 500,
        searchHint: "wc remontti purku hinta",
      },
      {
        id: "vesieristys",
        label: "Vesieristys ja laatoitus",
        description: "Vesieristys, laatoitus ja saumaus.",
        unit: "per_primary",
        amount: 600,
        minAmount: 800,
        searchHint: "wc laatoitus hinta",
      },
      {
        id: "lvi",
        label: "LVI-työt",
        description: "Putkien uusinta tai siirrot.",
        unit: "fixed",
        amount: 800,
        searchHint: "wc putkityöt hinta",
      },
      {
        id: "kalusteet",
        label: "Kalusteet",
        description: "Wc-istuin, allas ja hanat.",
        unit: "fixed",
        amount: 600,
        searchHint: "wc kalusteet hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko wc-remontti maksaa?",
        a: "Tyypillisesti 3 000–8 000 € riippuen laajuudesta.",
      },
    ],
    scopeTitle: "WC-remontin kustannukset",
    scopeParagraphs: [
      "Pienessä tilassa kiinteät minimikustannukset nostavat neliöhintaa.",
    ],
    ctaLabel: "Kilpailuta wc-remontti",
  }),

  buildCalculator({
    slug: "sauna",
    title: "Saunaremontin hintalaskuri",
    pageTitle: "Saunaremontti laskuri — arvioi remontin hinta",
    metaDescription: "Arvioi saunaremontin hinta: panelit, kiuas, LVI ja sähkö.",
    intro: "Saunaremontti voi olla pintojen uusinta tai täysi remontti putkineen.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Saunan lattia-ala", 4, { min: 2, max: 15 }),
    lines: [
      {
        id: "purku",
        label: "Purkutyöt",
        description: "Vanhojen panelien ja kalusteiden purku.",
        unit: "fixed",
        amount: 600,
        searchHint: "saunan purku hinta",
      },
      {
        id: "panelit",
        label: "Panelit ja lauteet",
        description: "Seinä- ja kattopanelit, lauteet ja listat.",
        unit: "per_primary",
        amount: 350,
        searchHint: "saunapaneeli hinta neliö",
      },
      {
        id: "kiuas",
        label: "Kiuas",
        description: "Sähkö- tai puukiuas (hankinta).",
        unit: "fixed",
        amount: 800,
        searchHint: "saunan kiuas hinta",
      },
      {
        id: "sahko-lvi",
        label: "Sähkö- ja LVI-työt",
        description: "Kiukaan sähkö, vesipisteet ja viemäri.",
        unit: "fixed",
        amount: 1200,
        searchHint: "saunan sähköasennus hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko saunaremontti maksaa?",
        a: "Pintaremontti 3 000–6 000 €. Täysi remontti 8 000–15 000 €.",
      },
    ],
    scopeTitle: "Saunaremontin kustannukset",
    scopeParagraphs: [
      "Sähkökiukaan asennus vaatii riittävän tehon — tarkista sulake.",
    ],
    ctaLabel: "Kilpailuta saunaremontti",
  }),

  buildCalculator({
    slug: "lattia-sisä",
    title: "Sisälattian hintalaskuri",
    pageTitle: "Sisälattia laskuri — parketti, laminaatti, laatta",
    metaDescription: "Arvioi sisälattian uusinnan hinta.",
    intro: "Lattiamateriaali ja alustan kunto vaikuttavat hintaan merkittävästi.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Lattia-ala", 25, { min: 5, max: 150 }),
    tiers: [
      { id: "laminaatti", label: "Laminaatti", overrides: { materiaali: 25 } },
      { id: "parketti", label: "Parketti", overrides: { materiaali: 55 } },
      { id: "laatta", label: "Laatta", overrides: { materiaali: 45, tyo: 35 } },
    ],
    defaultTierId: "laminaatti",
    lines: [
      {
        id: "purku",
        label: "Vanhan lattian purku",
        description: "Vanhan pinnoitteen purku ja jäte.",
        unit: "per_primary",
        amount: 8,
        minAmount: 200,
        searchHint: "lattian purku hinta neliö",
      },
      {
        id: "tasoitus",
        label: "Tasoitus ja pohjatyöt",
        description: "Alustan tasoitus ja eristeet.",
        unit: "per_primary",
        amount: 15,
        searchHint: "lattian tasoitus hinta neliö",
      },
      {
        id: "materiaali",
        label: "Lattiamateriaali",
        description: "Laminaatti, parketti tai laatta.",
        unit: "per_primary",
        amount: 25,
        searchHint: "laminaatti hinta neliö",
      },
      {
        id: "tyo",
        label: "Asennustyö",
        description: "Materiaalin asennus ja viimeistely.",
        unit: "per_primary",
        amount: 20,
        searchHint: "lattian asennus hinta neliö",
      },
    ],
    faq: [
      {
        q: "Paljonko uusi lattia maksaa?",
        a: "Laminaatti 40–70 €/m², parketti 70–120 €/m² asennettuna.",
      },
    ],
    scopeTitle: "Sisälattian kustannukset",
    scopeParagraphs: [
      "Epätasainen alusta vaatii tasoituksen — se nostaa hintaa.",
    ],
    ctaLabel: "Kilpailuta lattiatyö",
  }),

  buildCalculator({
    slug: "seinamaalaus",
    title: "Seinämaalauksen hintalaskuri",
    pageTitle: "Seinämaalaus laskuri — arvioi maalaustyön hinta",
    metaDescription: "Arvioi seinämaalauksen hinta huonekohtaisesti.",
    intro: "Maalaustyön hinta riippuu pinta-alasta, kerrosten määrästä ja pintojen kunnosta.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Seinäpinta-ala", 40, { min: 10, max: 300 }),
    lines: [
      {
        id: "pohjatyot",
        label: "Pohjatyöt",
        description: "Pesu, tasoitteet ja pohjamaalaus.",
        unit: "per_primary",
        amount: 8,
        searchHint: "seinämaalaus pohjatyöt hinta neliö",
      },
      {
        id: "maalaus",
        label: "Maalaustyö",
        description: "Kaksi kerrosta pintamaalia.",
        unit: "per_primary",
        amount: 12,
        minAmount: 300,
        searchHint: "seinämaalaus hinta neliö",
      },
      {
        id: "maali",
        label: "Maalit ja tarvikkeet",
        description: "Laadukas sisämaali ja tarvikkeet.",
        unit: "per_primary",
        amount: 4,
        searchHint: "sisämaali hinta neliö",
      },
    ],
    faq: [
      {
        q: "Paljonko seinämaalaus maksaa?",
        a: "Tyypillisesti 20–35 €/m² ammattilaisen tekemänä.",
      },
    ],
    scopeTitle: "Seinämaalauksen kustannukset",
    scopeParagraphs: [
      "Korkeat huoneet ja huonokuntoiset pinnat nostavat hintaa.",
    ],
    ctaLabel: "Kilpailuta maalaustyö",
  }),

  buildCalculator({
    slug: "laatoitus-sisa",
    title: "Sisälaatoituksen hintalaskuri",
    pageTitle: "Sisälaatoitus laskuri — arvioi laatoituksen hinta",
    metaDescription: "Arvioi sisätilojen laatoituksen hinta.",
    intro: "Laatoitus keittiön välitilassa, eteisessä tai muussa sisätilassa.",
    areaSlug: "sisatilat",
    primaryInput: sqmInput("Laatoitusala", 8, { min: 2, max: 50 }),
    lines: [
      {
        id: "tyo",
        label: "Laatoitustyö",
        description: "Laatoitus ja saumaus (työn osuus).",
        unit: "per_primary",
        amount: 45,
        minAmount: 300,
        searchHint: "laatoitus työ hinta neliö",
      },
      {
        id: "laatat",
        label: "Laatat ja materiaalit",
        description: "Laatat, laasti ja sauma-aine.",
        unit: "per_primary",
        amount: 35,
        searchHint: "laatta hinta neliö",
      },
      {
        id: "pohja",
        label: "Pohjatyöt",
        description: "Tasoitus ja vesieristys tarvittaessa.",
        unit: "per_primary",
        amount: 20,
        searchHint: "laatoituksen pohjatyöt hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko laatoitus maksaa?",
        a: "Sisälaatoitus tyypillisesti 80–120 €/m² asennettuna.",
      },
    ],
    scopeTitle: "Sisälaatoituksen kustannukset",
    scopeParagraphs: [
      "Pieni ala on kalliimpaa neliöltä kiinteiden käyntikustannusten vuoksi.",
    ],
    ctaLabel: "Kilpailuta laatoitus",
  }),
];
