import { buildCalculator, countInput, meterInput, sqmInput } from "../helpers";
import type { CalculatorConfig } from "../types";

export const ULKOKUORI_CALCULATORS: CalculatorConfig[] = [
  buildCalculator({
    slug: "ikkunat",
    title: "Ikkunoiden uusinnan hintalaskuri",
    pageTitle: "Ikkunat laskuri — arvioi ikkunaremontin hinta",
    metaDescription: "Arvioi ikkunoiden uusinnan hinta: ikkunat, asennus ja listat.",
    intro: "Uudet ikkunat parantavat energiatehokkuutta. Hinta riippuu ikkunoiden määrästä, koosta ja materiaalista.",
    areaSlug: "ulkokuori",
    primaryInput: countInput("Ikkunoita", 8, "kpl", { max: 30 }),
    lines: [
      {
        id: "ikkunat",
        label: "Ikkunat (materiaali)",
        description: "Energiatehokkaat ikkunat (puu/alumiini/muovi).",
        unit: "per_primary",
        amount: 450,
        searchHint: "ikkuna hinta kpl",
      },
      {
        id: "asennus",
        label: "Asennus ja tiivistys",
        description: "Vanhojen purku, asennus, listat ja tiivistys.",
        unit: "per_primary",
        amount: 150,
        searchHint: "ikkunan asennus hinta",
      },
      {
        id: "listat",
        label: "Sisä- ja ulkolistat",
        description: "Listat ja viimeistely.",
        unit: "per_primary",
        amount: 40,
        searchHint: "ikkunalista hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko ikkunat maksavat?",
        a: "Yksittäinen ikkuna 500–900 € asennettuna. Koko talo 8 000–20 000 €.",
      },
    ],
    scopeTitle: "Ikkunaremontin kustannukset",
    scopeParagraphs: [
      "Kolminkertaiset lasit parantavat energiatehokkuutta merkittävästi.",
    ],
    ctaLabel: "Kilpailuta ikkunat",
  }),

  buildCalculator({
    slug: "ovet-ulko",
    title: "Ulko-oven hintalaskuri",
    pageTitle: "Ulko-ovi laskuri — arvioi oven hinta",
    metaDescription: "Arvioi ulko-oven uusinnan hinta.",
    intro: "Etuovi, terassi-ovi tai autotallin ovi — hinta riippuu tyypistä ja turvallisuusvaatimuksista.",
    areaSlug: "ulkokuori",
    primaryInput: countInput("Ovia", 1, "kpl", { max: 5 }),
    lines: [
      {
        id: "ovi",
        label: "Ovi (materiaali)",
        description: "Ulko-ovi lukkoineen.",
        unit: "per_primary",
        amount: 1200,
        searchHint: "ulko-ovi hinta",
      },
      {
        id: "asennus",
        label: "Asennus",
        description: "Vanhan purku, asennus ja tiivistys.",
        unit: "per_primary",
        amount: 400,
        searchHint: "ulko-oven asennus hinta",
      },
      {
        id: "karmi",
        label: "Karmi ja listat",
        description: "Karmi, kynnykset ja listat.",
        unit: "per_primary",
        amount: 200,
        searchHint: "ovikarmi hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko ulko-ovi maksaa?",
        a: "Tyypillisesti 1 500–2 500 € asennettuna.",
      },
    ],
    scopeTitle: "Ulko-oven kustannukset",
    scopeParagraphs: [
      "Turvaovet ja älylukot nostavat hintaa.",
    ],
    ctaLabel: "Kilpailuta ulko-ovi",
  }),

  buildCalculator({
    slug: "katto-pelti",
    title: "Kattoremontin hintalaskuri",
    pageTitle: "Kattoremontti hinta — ilmainen laskuri",
    metaDescription: "Laske kattoremontin hinta: purku, kate, rännit ja työt. Suuntaa-antava arvio — kilpailuta urakoitsijat ilmaiseksi.",
    intro: "Kattoremontin hinta riippuu katon pinta-alasta, materiaalista ja alustan kunnosta.",
    areaSlug: "ulkokuori",
    primaryInput: sqmInput("Katon pinta-ala", 120, { min: 40, max: 400, step: 10 }),
    lines: [
      {
        id: "purku",
        label: "Vanhan kattomateriaalin purku",
        description: "Vanhan kateen purku ja jätehuolto.",
        unit: "per_primary",
        amount: 15,
        minAmount: 1500,
        searchHint: "kattomateriaalin purku hinta neliö",
      },
      {
        id: "aluskate",
        label: "Aluskate ja koolaus",
        description: "Aluskate, koolaus ja tuuletus.",
        unit: "per_primary",
        amount: 25,
        searchHint: "kattopelti aluskate hinta neliö",
      },
      {
        id: "kate",
        label: "Kattomateriaali (pelti/tiili)",
        description: "Pelti, tiili tai huopa kattomateriaalina.",
        unit: "per_primary",
        amount: 45,
        searchHint: "kattopelti hinta neliö",
      },
      {
        id: "tyo",
        label: "Asennustyö",
        description: "Kattomateriaalin asennus ja viimeistely.",
        unit: "per_primary",
        amount: 35,
        searchHint: "kattoremontti hinta neliö",
      },
      {
        id: "rannit",
        label: "Rännit ja kourut",
        description: "Uudet rännit ja kourujen asennus.",
        unit: "fixed",
        amount: 2000,
        searchHint: "rännit hinta talo",
      },
    ],
    faq: [
      {
        q: "Paljonko kattoremontti maksaa?",
        a: "Laskurin oletus ({defaultSize}) antaa {perUnitRange}/{primaryUnit}, kokonaisuutena {totalRange}. Todennäköinen taso on noin {totalMid}.",
      },
    ],
    scopeTitle: "Kattoremontin kustannukset",
    scopeParagraphs: [
      "Kattoremontti on merkittävä investointi — huono kate aiheuttaa vesivahinkoja.",
      "Rännit kannattaa uusia samalla kun kate vaihdetaan.",
    ],
    ctaLabel: "Kilpailuta kattoremontti",
  }),

  buildCalculator({
    slug: "rannit",
    title: "Rännien uusinnan hintalaskuri",
    pageTitle: "Rännit laskuri — arvioi ränniremontin hinta",
    metaDescription: "Arvioi rännien ja kourujen uusinnan hinta.",
    intro: "Uudet rännit estävät sadevesivahinkoja julkisivuun ja perustuksiin.",
    areaSlug: "ulkokuori",
    primaryInput: meterInput("Rännien pituus", 30, { min: 10, max: 80 }),
    lines: [
      {
        id: "rannit",
        label: "Rännit ja kourut (materiaali)",
        description: "Alumiini- tai sinkkirännit tarvikkeineen.",
        unit: "per_primary",
        amount: 25,
        searchHint: "rännit hinta metri",
      },
      {
        id: "asennus",
        label: "Asennus",
        description: "Vanhojen purku, uusien asennus ja liitokset.",
        unit: "per_primary",
        amount: 20,
        searchHint: "rännien asennus hinta metri",
      },
      {
        id: "sadevesi",
        label: "Sadevesijärjestelmä",
        description: "Putket maahan ja kaivot.",
        unit: "fixed",
        amount: 500,
        searchHint: "sadevesi putki hinta",
      },
    ],
    faq: [
      {
        q: "Paljonko rännit maksavat?",
        a: "Omakotitalossa tyypillisesti 1 500–4 000 €.",
      },
    ],
    scopeTitle: "Ränniremontin kustannukset",
    scopeParagraphs: [
      "Korkeat räystäät ja vaikea pääsy nostavat työkustannuksia.",
    ],
    ctaLabel: "Kilpailuta rännit",
  }),

  buildCalculator({
    slug: "ulkomaalaus",
    title: "Ulkomaalauksen hintalaskuri",
    pageTitle: "Ulkomaalaus laskuri — arvioi maalaustyön hinta",
    metaDescription: "Arvioi talon ulkomaalauksen hinta.",
    intro: "Ulkomaalaus suojaa julkisivua. Hintaan vaikuttavat pinta-ala, korkeus ja pintojen kunto.",
    areaSlug: "ulkokuori",
    primaryInput: sqmInput("Maalattava pinta-ala", 150, { min: 50, max: 500, step: 10 }),
    lines: [
      {
        id: "pesu",
        label: "Pesu ja pohjatyöt",
        description: "Pintojen pesu, hiominen ja pohjamaalaus.",
        unit: "per_primary",
        amount: 8,
        searchHint: "ulkomaalaus pesu hinta neliö",
      },
      {
        id: "maalaus",
        label: "Maalaustyö",
        description: "Kaksi kerrosta ulkomaalia.",
        unit: "per_primary",
        amount: 18,
        minAmount: 1500,
        searchHint: "ulkomaalaus hinta neliö",
      },
      {
        id: "maali",
        label: "Maalit ja tarvikkeet",
        description: "Laadukas ulkomaali ja tarvikkeet.",
        unit: "per_primary",
        amount: 6,
        searchHint: "ulkomaali hinta neliö",
      },
      {
        id: "telinetyo",
        label: "Telinetyöt",
        description: "Rakennustelineet tai nostin.",
        unit: "fixed",
        amount: 800,
        searchHint: "rakennusteline hinta maalaus",
      },
    ],
    faq: [
      {
        q: "Paljonko ulkomaalaus maksaa?",
        a: "Tyypillisesti 25–45 €/m² eli omakotitalo 5 000–12 000 €.",
      },
    ],
    scopeTitle: "Ulkomaalauksen kustannukset",
    scopeParagraphs: [
      "Korkeat rakennukset vaativat telineet — ne lisäävät kustannuksia.",
    ],
    ctaLabel: "Kilpailuta ulkomaalaus",
  }),

  buildCalculator({
    slug: "julkisivu-verhous",
    title: "Julkisivuverhouksen hintalaskuri",
    pageTitle: "Julkisivuverhous laskuri",
    metaDescription: "Arvioi julkisivuverhouksen hinta.",
    intro: "Uusi verhous puulla, komposiitilla tai peltilevyllä.",
    areaSlug: "ulkokuori",
    primaryInput: sqmInput("Verhouksen pinta-ala", 120, { min: 40, max: 400, step: 10 }),
    lines: [
      {
        id: "verhous",
        label: "Verhousmateriaali",
        description: "Paneelit, laudat tai komposiitti.",
        unit: "per_primary",
        amount: 35,
        searchHint: "julkisivuverhous hinta neliö",
      },
      {
        id: "tyo",
        label: "Asennustyö",
        description: "Koolaus, asennus ja viimeistely.",
        unit: "per_primary",
        amount: 40,
        searchHint: "julkisivuverhous asennus hinta",
      },
      {
        id: "eriste",
        label: "Tuulensuoja ja eriste",
        description: "Tuulensuojalevy ja lisäeriste tarvittaessa.",
        unit: "per_primary",
        amount: 15,
        searchHint: "tuulensuojalevy hinta neliö",
      },
    ],
    faq: [
      {
        q: "Paljonko julkisivuverhous maksaa?",
        a: "Tyypillisesti 80–120 €/m² asennettuna.",
      },
    ],
    scopeTitle: "Julkisivuverhouksen kustannukset",
    scopeParagraphs: [
      "Vanhan verhouksen kunto vaikuttaa — homeinen alusta vaatii purun.",
    ],
    ctaLabel: "Kilpailuta julkisivuverhous",
  }),

  buildCalculator({
    slug: "julkisivu-rapaus",
    title: "Julkisivurappauksen hintalaskuri",
    pageTitle: "Julkisivurappaus laskuri",
    metaDescription: "Arvioi julkisivun rapauksen korjauksen hinta.",
    intro: "Halkeamat, irtoileva rapaus tai uusi pinta — rapaus suojaa julkisivua.",
    areaSlug: "ulkokuori",
    primaryInput: sqmInput("Rapattava pinta-ala", 100, { min: 20, max: 400, step: 10 }),
    lines: [
      {
        id: "korjaus",
        label: "Halkeamien korjaus",
        description: "Halkeamien avaus, täyttö ja vahvistus.",
        unit: "per_primary",
        amount: 12,
        searchHint: "julkisivu halkeama korjaus hinta",
      },
      {
        id: "rapaus",
        label: "Rapaus / tiheärapaus",
        description: "Uusi rapauskerros tai paikallinen korjaus.",
        unit: "per_primary",
        amount: 25,
        minAmount: 1500,
        searchHint: "julkisivurappaus hinta neliö",
      },
      {
        id: "maalaus",
        label: "Pintakäsittely / maalaus",
        description: "Maalaus tai silikonointi rapauksen päälle.",
        unit: "per_primary",
        amount: 10,
        searchHint: "julkisivumaalaus hinta neliö",
      },
    ],
    faq: [
      {
        q: "Paljonko julkisivurappaus maksaa?",
        a: "Korjausrapaus 40–70 €/m². Täysi uusinta 80–120 €/m².",
      },
    ],
    scopeTitle: "Julkisivurappauksen kustannukset",
    scopeParagraphs: [
      "Kosteusvauriot on korjattava ennen uutta rapausta.",
    ],
    ctaLabel: "Kilpailuta julkisivurappaus",
  }),
];
